### ISSUE TITLE
CUDA 11.3

### ISSUE THREAD

**Issue by lithedress** [LaurentMazare/tch-rs#474] opened 2022-04-12 08:35 UTC
The URL [https://download.pytorch.org/libtorch/cu111/libtorch-shared-with-deps-1.11.0%2Bcu111.zip](https://download.pytorch.org/libtorch/cu111/libtorch-shared-with-deps-1.11.0%2Bcu111.zip) is AccessDenied now.
An upgrade to `cu113` is necessary.

**Comment by LaurentMazare** [comment] 2022-04-12 21:40
Thanks for reporting this issue, indeed `cu113` seems to work fine so the build script has been updated to reflect this.

**Comment by Mec-iS** [comment] 2022-08-21 20:29
With CUDA 11.6, setting the `TORCH_CUDA_VERSION=cu116`:
```
Unexpected response code 403 for https://download.pytorch.org/libtorch/cu116/libtorch-cxx11-abi-shared-with-deps-1.12.0.zip'
```

**Comment by LaurentMazare** [comment] 2022-08-22 08:36
@Mec-iS that's odd. I just tried with the latest github tip and `TORCH_CUDA_VERSION=cu116` and it worked well. Is it possible that you were using an older version of this crate which did not support `cu116`? This would have resulted in the error message you saw, anyway I just changed the build script to make understanding the root cause a bit easier.

**Comment by Mec-iS** [comment] 2022-08-22 09:49
I was installing version `0.8.0` using `crate`. I don't think the version is the problem as the link I posted above indeed return "Access Denied" if you try to visit it. The link that worked for me is `https://download.pytorch.org/libtorch/cu116/libtorch-cxx11-abi-shared-with-deps-1.12.1%2Bcu116.zip`
See the name of the file at the end is different.

**Comment by LaurentMazare** [comment] 2022-08-22 09:52
Support for `cu116` was added after the crate 0.8.0 release so this explains the error you saw, the next version will have a better error message for this.

**Comment by Mec-iS** [comment] 2022-08-22 10:02
ok thanks. the latest crate in crates.io is 0.8.0, where I can find the latest ones?

**Comment by LaurentMazare** [comment] 2022-08-22 10:08
The latest version is 0.8.0, we usually make crate releases only on new versions of `libtorch` so the next one would be when PyTorch 1.13 is released. Maybe you can point your `Cargo.toml` at some recent github revision for the time being?

**Comment by LaurentMazare** [comment] 2023-04-25 15:10
Closing this as the 1.13 version has been released for quite some time now.

**Closed by LaurentMazare** 2023-04-25 15:10 UTC
