### ISSUE TITLE
RuntimeError: cuda runtime error (34) : device not ready

### ISSUE THREAD

**Issue by kriti0111** [LaurentMazare/tch-rs#225] opened 2020-07-01 17:28 UTC
I have installed libtorch as mentioned in the readme for this repo. 
My CUDA version is 10.0.130. 
torch-sys v0.1.7
tch v0.1.7

I'm trying to load saved models and attempting inference. The models are loaded successfully.
But I'm getting the following error just when I'm about to infer those models. 
```
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=278 error=34 : device not ready
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorchError { c_error: "The following operation failed in the TorchScript interpreter.\nTraceback of TorchScript, serialized code (most recent call last):\n  File \"code/__torch__/lib/training/model/___torch_mangle_3007.py\", line 35, in forward\n  
 _10 = (self.mixed_6a).forward((_7).forward(_8, ), )\n    
_11 = self.repeat_2\n    
_12 = (self.mixed_7a).forward((_9).forward(_10, ), )\n  
~~~~~~~~~~~ <--- HERE\n.     
_13 = self.conv2d_7b\n    
_14 = (self.block8).forward((_11).forward(_12, ), )\n  File \"code/__torch__/torch/nn/modules/container/___torch_mangle_2765.py\", line 27, in forward\n    argument_1: Tensor) -> Tensor:\n    _0 = getattr(self, \"1\")\n    _1 = (getattr(self, \"0\")).forward(argument_1, )\n          ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n.   
_2 = getattr(self, \"3\")\n.    
_3 = (getattr(self, \"2\")).forward((_0).forward(_1, ), )\n  File \"code/__torch__/lib/training/model/___torch_mangle_2384.py\", line 15, in forward\n    _3 = (self.branch0).forward(argument_1, )\n    input = torch.cat([_3, (_2).forward(argument_1, )], 1)\n    _4 = torch.mul((_1).forward(input, ), CONSTANTS.c1)\n                    
~~~~~~~~~~~ <--- HERE\n.   
 input0 = torch.add(_4, argument_1, alpha=1)\n    return (_0).forward(input0, )\n  File \"code/__torch__/lib/training/model/___torch_mangle_2384.py\", line 14, in forward\n    _2 = self.branch1\n    
_3 = (self.branch0).forward(argument_1, )\n    input = torch.cat([_3, (_2).forward(argument_1, )], 1)\n            
~~~~~~~~~ <--- HERE\n   
_4 = torch.mul((_1).forward(input, ), CONSTANTS.c1)\n    input0 = torch.add(_4, argument_1, alpha=1)\n\nTraceback of TorchScript,  
<module>\nRuntimeError: cuda runtime error (34) : device not ready at ../aten/src/THC/THCCachingHostAllocator.cpp:278\n" }'
```

The code snippet where it errors out - 
``` 
   let imgTensorCuda = imgTensor.to_device(tch::Device::cuda_if_available());
    // Apply the forward pass of the model to get the logits.
    let fcOutput = imgTensorCuda
        .unsqueeze(0)
        .apply(fcModel);
```
`fcModel` is the path to the saved torch model

Any idea what the issue could be?

**Comment by LaurentMazare** [comment] 2020-07-01 20:01
I've never seen such an error. Not sure how you created `fcModel`, if this was saved from a python script maybe you could try to save a cpu version and see if this works. Also it may be worth checking whether `tch-rs` correctly detected your gpu by running `tch::Cuda::is_available()` or `tch::Cuda::device_count`.

**Comment by kriti0111** [comment] 2020-07-02 03:19
Yes, `fcModel` was saved from a python script.
Also, `tch-rs` detected my GPU. Running this `tch::Cuda::is_available()` gives me `CUDA(0)`

**Comment by kriti0111** [comment] 2020-07-02 07:17
Also tried saving a CPU version and running that instead, it works perfectly. 

What could be the problem with the GPU version? The way the CUDA tensor is created?

**Comment by LaurentMazare** [comment] 2020-07-02 09:20
Ok, good thing that it's working with the CPU.
Just to be sure, `fcModel` was created on the same box as where you're running the rust code?
If not and the number of gpus are different, that could explain the issue.

**Comment by LaurentMazare** [comment] 2020-11-07 10:25
Closing as no recent update, feel free to re-open if the issue is still there.

**Closed by LaurentMazare** 2020-11-07 10:25 UTC

**Comment by Scheaven** [comment] 2020-11-17 03:31
I met the same problem,how did you slove it!
