### ISSUE TITLE
RuntimeError: code is too big

### ISSUE THREAD

**Issue by fariadif** [LaurentMazare/tch-rs#226] opened 2020-07-03 13:30 UTC
Hello

I am having troubles to infer some inputs using `forward_ts` on my Github CI application.
I have some tests passing on my local machine, but the CI docker fails every once and while on the same part of the code.
The curious is that the same tests pass on the CI container when the cache is clean. It seems purely a memory-related problem.
The error log is the following:

```
The` following operation failed in the TorchScript interpreter.\n
Traceback of TorchScript (most recent call last):\n  
File \"code/model.py\", line 20, in forward\n 
input_16 = torch.threshold(input_15, 0., 0.)\n  
input_17 = torch.avg_pool1d(input_16, [2], [2], [0], False, True)\n  
input_18 = torch._convolution(input_17, getattr(getattr(self.layers, \"6\"), \"0\").weight, getattr(getattr(self.layers, \"6\"), \"0\").bias, [1], [0], [1], False, [0], 1, False, False, True)\n 
            ~~~~~~~~~~~~~~~~~~ <--- HERE\n  
x = torch.adaptive_avg_pool1d(input_18, [1])\n  input = torch.squeeze(x, -1)\n

RuntimeError: code is too big\n"
```
Below is the code snippet where the errors appear. The model uses padding equal to 0

```
tch::no_grad(|| Ok(CModule::load(path)?.forward_ts(&[input_batch])?))
```

More info:
```
My local machine uses Ubuntu 19.10 and the CI container is rust:latest
torch-sys v0.1.7
tch v0.1.7
MKL-DNN v0.21.1
```
I need some help to understand why this is happening.
Thank you very much.

**Comment by LaurentMazare** [comment] 2020-07-03 13:42
I've never seen this error but googling this a bit, this seems to be caused by mkl-dnn, e.g. https://github.com/pytorch/pytorch/issues/24174
However in the case of this previous issue, the problem should be fixed in the mkl-dnn version you use.
Maybe your CI container does not have enough memory and you could try running your integration tests with a smaller batch size?

**Comment by LaurentMazare** [comment] 2020-11-07 10:25
Closing as no further updates and this was probably caused by not having enough memory available.

**Closed by LaurentMazare** 2020-11-07 10:25 UTC
