### ISSUE TITLE
Release mode cannot find cuda

### ISSUE THREAD

**Issue by dbsxdbsx** [LaurentMazare/tch-rs#489] opened 2022-05-27 10:08 UTC
On Win10 with cuda 11.3, and tch-rs 0.7.2 and [torchlib 1.11.0_cuda11.3](https://pytorch.org/get-started/locally/) of release version, when calling ` tch::Device::cuda_if_available(),` in release mode, it  turns to using cpu. If  it is forced to using cuda by calling `tch::Device::Cuda(0)`, then it runs into error.

**Comment by RundownRhino** [comment] 2022-06-02 19:44
@dbsxdbsx Had the same issue. After some searching on the repo, realised this is a duplicate of https://github.com/LaurentMazare/tch-rs/issues/291. The solution, as per https://github.com/LaurentMazare/tch-rs/issues/291#issuecomment-890404057=, is to add
```rust
tch::maybe_init_cuda();
```
before you try to create a `Cuda(0)` device. That fixes the issue for me.

**Comment by dbsxdbsx** [comment] 2022-06-03 07:11
> @dbsxdbsx Had the same issue. After some searching on the repo, realised this is a duplicate of #291. The solution, as per [#291 (comment)](https://github.com/LaurentMazare/tch-rs/issues/291#issuecomment-890404057), is to add
> 
> ```rust
> tch::maybe_init_cuda();
> ```
> 
> before you try to create a `Cuda(0)` device. That fixes the issue for me.

@RundownRhino , thanks your advice. After putting `tch::maybe_init_cuda();` right before `tch::Device::Cuda(0);`, now it is not only workable when choosing `Cuda`, but also workable when choosing `cuda_if_available()`:

```rust
  let device = loop {
            let cur_index = get_usize_num_from_user_input_str();
            match cur_index {
                1 => break tch::Device::cuda_if_available(),
                2 => break tch::Device::Cpu,
                3 => {
                    tch::maybe_init_cuda();  // modified here
                    break tch::Device::Cuda(0);
                }
                _ => println!("error input"),
            }
        };
```
I am wondering  why `tch::maybe_init_cuda()` would affect `tch::Device::cuda_if_available()`.   
And still, I think `tch::maybe_init_cuda();` is still a workround, there should not need to write this line.

**Comment by LaurentMazare** [comment] 2023-05-14 11:04
`tch::maybe_init_cuda` is certainly a hacky workaround but the best we get so far as afaik it's not easy to specify the linker flags in order and ensure that they will be used to link the final binaries. Closing this issue for now until we find a better way to handle this.

**Closed by LaurentMazare** 2023-05-14 11:04 UTC
