### ISSUE TITLE
What is the best way to save tensor to disk?

### ISSUE THREAD

**Issue by dbsxdbsx** [LaurentMazare/tch-rs#410] opened 2021-09-04 16:11 UTC
When doing with reinforcement learning project, I have a struct like this:
```rust
Struct {
obs: vec<Tensor>,
action: vec<Tensor>,
...
}
```
I need to save the whole instance of the struct to disk, so that I could load it latter when using it next time.
I know `Tenosr` has methods called `save` and `load` to do so, but it is just for  only one tensor object.  It is easy to see this way is not appropriate for this case.     

Then I came up the way that concating `vec<Tensor>` into a single tensor befor calling `save`. But I think this may be inefficient when the number of tensor is large, say 1,000,000.     

Is there some other approach to do so?  Like using seralization(like crate [serde](https://docs.serde.rs/serde/))

**Comment by LaurentMazare** [comment] 2021-09-18 12:00
For trainable weights, the easiest is probably to have your tensors come from a VarStore object, these can be written to a file and read from a file. That's pretty much how all the examples work, e.g. for [min-gpt](https://github.com/LaurentMazare/tch-rs/blob/master/examples/min-gpt/main.rs) you can search for `vs.save` and `vs.load`.

For other tensors, it's possible to serialize multiple of them (with names) via `Tensor::save_multi` and `Tensor::load_multi`, see for example the [serialization tests](https://github.com/LaurentMazare/tch-rs/blob/a0523edfb48081201aaa3b176f9deaaf424f5ec3/tests/serialization_tests.rs).

**Comment by LaurentMazare** [comment] 2023-04-25 21:50
Closing this as it has been a while, fwiw it looks like the latest error was caused by writing to a directory rather than to a file in this directory if I'm not missing something.

**Closed by LaurentMazare** 2023-04-25 21:50 UTC
